name: study example
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v18
            - run: make setup
            - run: make start
            - run: make lint
            - run: make test


